import type { CityTheme, ThemeKey } from '@/types/audit'

export const themes: Record<ThemeKey, CityTheme> = {
  'los-angeles': {
    key: 'los-angeles',
    label: 'Los Angeles',
    primaryColor: '#1A6FA8',
    secondaryColor: '#F5A623',
    accentColor: '#E8754A',
    backgroundColor: '#FFF9F0',
    cardColor: '#FFFFFF',
    textColor: '#1A2332',
    mutedColor: '#6B7C93',
    primaryRgb: '26, 111, 168',
    emoji: '🌴',
    tagline: 'Sun, surf, and strong SEO.',
  },
  'new-york': {
    key: 'new-york',
    label: 'New York',
    primaryColor: '#1A1A2E',
    secondaryColor: '#F7C948',
    accentColor: '#E63946',
    backgroundColor: '#F2F2F2',
    cardColor: '#FFFFFF',
    textColor: '#0D0D0D',
    mutedColor: '#6B6B6B',
    primaryRgb: '26, 26, 46',
    emoji: '🗽',
    tagline: 'If your SEO can make it here, it can make it anywhere.',
  },
  'miami': {
    key: 'miami',
    label: 'Miami',
    primaryColor: '#0D7377',
    secondaryColor: '#FF6B9D',
    accentColor: '#F7C5A0',
    backgroundColor: '#FFF0F5',
    cardColor: '#FFFFFF',
    textColor: '#1A1A2E',
    mutedColor: '#7B6B7A',
    primaryRgb: '13, 115, 119',
    emoji: '🌊',
    tagline: 'Hot takes. Hotter rankings.',
  },
  'seattle': {
    key: 'seattle',
    label: 'Seattle',
    primaryColor: '#2D6A4F',
    secondaryColor: '#74C69D',
    accentColor: '#52796F',
    backgroundColor: '#F0F4F1',
    cardColor: '#FFFFFF',
    textColor: '#1B2420',
    mutedColor: '#6B7C72',
    primaryRgb: '45, 106, 79',
    emoji: '☕',
    tagline: 'Brewed strong. Ranked higher.',
  },
  'chicago': {
    key: 'chicago',
    label: 'Chicago',
    primaryColor: '#1E3A8A',
    secondaryColor: '#DC2626',
    accentColor: '#60A5FA',
    backgroundColor: '#F0F4FF',
    cardColor: '#FFFFFF',
    textColor: '#0F172A',
    mutedColor: '#64748B',
    primaryRgb: '30, 58, 138',
    emoji: '🌬️',
    tagline: 'Windy City, rock-solid rankings.',
  },
  'austin': {
    key: 'austin',
    label: 'Austin',
    primaryColor: '#C2410C',
    secondaryColor: '#84A98C',
    accentColor: '#F59E0B',
    backgroundColor: '#FFF7ED',
    cardColor: '#FFFFFF',
    textColor: '#2D1810',
    mutedColor: '#78716C',
    primaryRgb: '194, 65, 12',
    emoji: '🎸',
    tagline: 'Keep your SEO weird and wonderful.',
  },
  'denver': {
    key: 'denver',
    label: 'Denver',
    primaryColor: '#2563EB',
    secondaryColor: '#B91C1C',
    accentColor: '#D97706',
    backgroundColor: '#EFF6FF',
    cardColor: '#FFFFFF',
    textColor: '#172554',
    mutedColor: '#6B7280',
    primaryRgb: '37, 99, 235',
    emoji: '🏔️',
    tagline: 'Mile-high visibility starts here.',
  },
  'portland': {
    key: 'portland',
    label: 'Portland',
    primaryColor: '#15803D',
    secondaryColor: '#C2410C',
    accentColor: '#65A30D',
    backgroundColor: '#F0FDF4',
    cardColor: '#FFFFFF',
    textColor: '#052E16',
    mutedColor: '#6B7280',
    primaryRgb: '21, 128, 61',
    emoji: '🌲',
    tagline: 'Evergreen content, evergreen growth.',
  },
  'nashville': {
    key: 'nashville',
    label: 'Nashville',
    primaryColor: '#B45309',
    secondaryColor: '#0F766E',
    accentColor: '#FCD34D',
    backgroundColor: '#FFFBEB',
    cardColor: '#FFFFFF',
    textColor: '#451A03',
    mutedColor: '#78716C',
    primaryRgb: '180, 83, 9',
    emoji: '🎵',
    tagline: 'Your SEO is about to go platinum.',
  },
  'new-orleans': {
    key: 'new-orleans',
    label: 'New Orleans',
    primaryColor: '#7C3AED',
    secondaryColor: '#FBBF24',
    accentColor: '#10B981',
    backgroundColor: '#F5F3FF',
    cardColor: '#FFFFFF',
    textColor: '#2E1065',
    mutedColor: '#7C6B8F',
    primaryRgb: '124, 58, 237',
    emoji: '🎷',
    tagline: 'Let the good rankings roll.',
  },
  'san-francisco': {
    key: 'san-francisco',
    label: 'San Francisco',
    primaryColor: '#475569',
    secondaryColor: '#F97316',
    accentColor: '#94A3B8',
    backgroundColor: '#F1F5F9',
    cardColor: '#FFFFFF',
    textColor: '#0F172A',
    mutedColor: '#64748B',
    primaryRgb: '71, 85, 105',
    emoji: '🌁',
    tagline: 'Foggy days, crystal-clear rankings.',
  },
  'boston': {
    key: 'boston',
    label: 'Boston',
    primaryColor: '#1E3A5F',
    secondaryColor: '#A62929',
    accentColor: '#3B82F6',
    backgroundColor: '#F0F5FF',
    cardColor: '#FFFFFF',
    textColor: '#0F172A',
    mutedColor: '#6B7280',
    primaryRgb: '30, 58, 95',
    emoji: '🏛️',
    tagline: 'Revolutionary SEO for revolutionary businesses.',
  },
  'atlanta': {
    key: 'atlanta',
    label: 'Atlanta',
    primaryColor: '#B45309',
    secondaryColor: '#166534',
    accentColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
    cardColor: '#FFFFFF',
    textColor: '#451A03',
    mutedColor: '#78716C',
    primaryRgb: '180, 83, 9',
    emoji: '🍑',
    tagline: 'Peachy keen on page one.',
  },
  'phoenix': {
    key: 'phoenix',
    label: 'Phoenix',
    primaryColor: '#EA580C',
    secondaryColor: '#D4A574',
    accentColor: '#FDBA74',
    backgroundColor: '#FFF7ED',
    cardColor: '#FFFFFF',
    textColor: '#431407',
    mutedColor: '#78716C',
    primaryRgb: '234, 88, 12',
    emoji: '🌵',
    tagline: 'Rising from the ashes of page two.',
  },
  'las-vegas': {
    key: 'las-vegas',
    label: 'Las Vegas',
    primaryColor: '#7C3AED',
    secondaryColor: '#FBBF24',
    accentColor: '#EC4899',
    backgroundColor: '#FAF5FF',
    cardColor: '#FFFFFF',
    textColor: '#2E1065',
    mutedColor: '#7C6B8F',
    primaryRgb: '124, 58, 237',
    emoji: '🎰',
    tagline: 'SEO so good, it feels like hitting the jackpot.',
  },
  'honolulu': {
    key: 'honolulu',
    label: 'Honolulu',
    primaryColor: '#0EA5E9',
    secondaryColor: '#EC4899',
    accentColor: '#F0ABFC',
    backgroundColor: '#F0F9FF',
    cardColor: '#FFFFFF',
    textColor: '#0C4A6E',
    mutedColor: '#64748B',
    primaryRgb: '14, 165, 233',
    emoji: '🌺',
    tagline: 'Aloha to your new competitors — they are behind you.',
  },
  default: {
    key: 'default',
    label: 'Your City',
    primaryColor: '#1A6FA8',
    secondaryColor: '#F5A623',
    accentColor: '#E8754A',
    backgroundColor: '#FFF9F0',
    cardColor: '#FFFFFF',
    textColor: '#1A2332',
    mutedColor: '#6B7C93',
    primaryRgb: '26, 111, 168',
    emoji: '📍',
    tagline: 'Local SEO, done right.',
  },
}

// Maps normalized city name input → theme key
const CITY_MAP: Record<string, ThemeKey> = {
  'los angeles': 'los-angeles',
  'la': 'los-angeles',
  'l.a.': 'los-angeles',
  'new york': 'new-york',
  'new york city': 'new-york',
  'nyc': 'new-york',
  'n.y.c.': 'new-york',
  'miami': 'miami',
  'seattle': 'seattle',
  'chicago': 'chicago',
  'austin': 'austin',
  'denver': 'denver',
  'portland': 'portland',
  'nashville': 'nashville',
  'new orleans': 'new-orleans',
  'nola': 'new-orleans',
  'san francisco': 'san-francisco',
  'sf': 'san-francisco',
  'frisco': 'san-francisco',
  'boston': 'boston',
  'atlanta': 'atlanta',
  'phoenix': 'phoenix',
  'las vegas': 'las-vegas',
  'vegas': 'las-vegas',
  'honolulu': 'honolulu',
}

/* Normalize a raw city string for matching:
 * - Trim whitespace
 * - Strip US state abbreviations and country suffixes (e.g. "Austin TX" → "austin")
 * - Lowercase for dictionary lookup
 */
function normalizeCity(raw: string): string {
  let s = raw.trim().toLowerCase()
  // Strip trailing state / country like "Austin TX", "Los Angeles, CA", "New York, USA"
  s = s.replace(/[,\s]+(?:al|ak|az|ar|ca|co|ct|de|fl|ga|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|oh|ok|or|pa|ri|sc|sd|tn|tx|ut|vt|va|wa|wv|wi|wy|usa|us)(?:\.)?$/i, '')
  s = s.trim()
  // Also strip just a trailing comma if it remains
  s = s.replace(/,$/, '')
  return s.trim()
}

export function getThemeForCity(city: string): CityTheme {
  const normalized = normalizeCity(city)
  const key = CITY_MAP[normalized]
  return themes[key ?? 'default']
}
