import type { CityTheme, ThemeKey } from '@/types/audit'

export const themes: Record<ThemeKey, CityTheme> = {
  'los-angeles': {
    key: 'los-angeles',
    label: 'Los Angeles',
    primaryColor: '#2563EB',
    secondaryColor: '#FFD600',
    accentColor: '#FF6B6B',
    backgroundColor: '#F0F4FF',
    cardColor: '#FFFFFF',
    textColor: '#1A1A2E',
    mutedColor: '#6B7280',
    primaryRgb: '37, 99, 235',
    emoji: '🌴',
    tagline: 'Sun, surf, and strong SEO.',
  },
  'new-york': {
    key: 'new-york',
    label: 'New York',
    primaryColor: '#1A1A2E',
    secondaryColor: '#FFD600',
    accentColor: '#FF6B6B',
    backgroundColor: '#F8F8FA',
    cardColor: '#FFFFFF',
    textColor: '#0D0D0D',
    mutedColor: '#6B7280',
    primaryRgb: '26, 26, 46',
    emoji: '🗽',
    tagline: 'If your SEO can make it here, it can make it anywhere.',
  },
  'miami': {
    key: 'miami',
    label: 'Miami',
    primaryColor: '#FF6B6B',
    secondaryColor: '#FFD600',
    accentColor: '#06B6D4',
    backgroundColor: '#FFF5F5',
    cardColor: '#FFFFFF',
    textColor: '#1A1A2E',
    mutedColor: '#78716C',
    primaryRgb: '255, 107, 107',
    emoji: '🌊',
    tagline: 'Hot takes. Hotter rankings.',
  },
  'seattle': {
    key: 'seattle',
    label: 'Seattle',
    primaryColor: '#0891B2',
    secondaryColor: '#22D3EE',
    accentColor: '#6366F1',
    backgroundColor: '#ECFEFF',
    cardColor: '#FFFFFF',
    textColor: '#164E63',
    mutedColor: '#6B7280',
    primaryRgb: '8, 145, 178',
    emoji: '☕',
    tagline: 'Brewed strong. Ranked higher.',
  },
  'chicago': {
    key: 'chicago',
    label: 'Chicago',
    primaryColor: '#2563EB',
    secondaryColor: '#DC2626',
    accentColor: '#FFD600',
    backgroundColor: '#EFF6FF',
    cardColor: '#FFFFFF',
    textColor: '#172554',
    mutedColor: '#6B7280',
    primaryRgb: '37, 99, 235',
    emoji: '🌬️',
    tagline: 'Windy City, rock-solid rankings.',
  },
  'austin': {
    key: 'austin',
    label: 'Austin',
    primaryColor: '#EA580C',
    secondaryColor: '#84CC16',
    accentColor: '#FFD600',
    backgroundColor: '#FFF7ED',
    cardColor: '#FFFFFF',
    textColor: '#431407',
    mutedColor: '#78716C',
    primaryRgb: '234, 88, 12',
    emoji: '🎸',
    tagline: 'Keep your SEO weird and wonderful.',
  },
  'denver': {
    key: 'denver',
    label: 'Denver',
    primaryColor: '#059669',
    secondaryColor: '#FFD600',
    accentColor: '#F97316',
    backgroundColor: '#ECFDF5',
    cardColor: '#FFFFFF',
    textColor: '#064E3B',
    mutedColor: '#6B7280',
    primaryRgb: '5, 150, 105',
    emoji: '🏔️',
    tagline: 'Mile-high visibility starts here.',
  },
  'portland': {
    key: 'portland',
    label: 'Portland',
    primaryColor: '#16A34A',
    secondaryColor: '#EA580C',
    accentColor: '#84CC16',
    backgroundColor: '#F0FDF4',
    cardColor: '#FFFFFF',
    textColor: '#14532D',
    mutedColor: '#6B7280',
    primaryRgb: '22, 163, 74',
    emoji: '🌲',
    tagline: 'Evergreen content, evergreen growth.',
  },
  'nashville': {
    key: 'nashville',
    label: 'Nashville',
    primaryColor: '#D97706',
    secondaryColor: '#7C3AED',
    accentColor: '#FFD600',
    backgroundColor: '#FFFBEB',
    cardColor: '#FFFFFF',
    textColor: '#451A03',
    mutedColor: '#78716C',
    primaryRgb: '217, 119, 6',
    emoji: '🎵',
    tagline: 'Your SEO is about to go platinum.',
  },
  'new-orleans': {
    key: 'new-orleans',
    label: 'New Orleans',
    primaryColor: '#7C3AED',
    secondaryColor: '#FFD600',
    accentColor: '#10B981',
    backgroundColor: '#F5F3FF',
    cardColor: '#FFFFFF',
    textColor: '#2E1065',
    mutedColor: '#7C6B8F',
    primaryRgb: '124, 58, 237',
    emoji: '🎷',
    tagline: 'Let the good rankings roll.',
  },
  'san-francisco': {
    key: 'san-francisco',
    label: 'San Francisco',
    primaryColor: '#4F46E5',
    secondaryColor: '#F97316',
    accentColor: '#818CF8',
    backgroundColor: '#EEF2FF',
    cardColor: '#FFFFFF',
    textColor: '#1E1B4B',
    mutedColor: '#6B7280',
    primaryRgb: '79, 70, 229',
    emoji: '🌁',
    tagline: 'Foggy days, crystal-clear rankings.',
  },
  'boston': {
    key: 'boston',
    label: 'Boston',
    primaryColor: '#1E3A5F',
    secondaryColor: '#DC2626',
    accentColor: '#3B82F6',
    backgroundColor: '#F0F5FF',
    cardColor: '#FFFFFF',
    textColor: '#0F172A',
    mutedColor: '#6B7280',
    primaryRgb: '30, 58, 95',
    emoji: '🏛️',
    tagline: 'Revolutionary SEO for revolutionary businesses.',
  },
  'atlanta': {
    key: 'atlanta',
    label: 'Atlanta',
    primaryColor: '#EA580C',
    secondaryColor: '#16A34A',
    accentColor: '#FFD600',
    backgroundColor: '#FFFBEB',
    cardColor: '#FFFFFF',
    textColor: '#431407',
    mutedColor: '#78716C',
    primaryRgb: '234, 88, 12',
    emoji: '🍑',
    tagline: 'Peachy keen on page one.',
  },
  'phoenix': {
    key: 'phoenix',
    label: 'Phoenix',
    primaryColor: '#DC2626',
    secondaryColor: '#FDBA74',
    accentColor: '#FFD600',
    backgroundColor: '#FFF7ED',
    cardColor: '#FFFFFF',
    textColor: '#431407',
    mutedColor: '#78716C',
    primaryRgb: '220, 38, 38',
    emoji: '🌵',
    tagline: 'Rising from the ashes of page two.',
  },
  'las-vegas': {
    key: 'las-vegas',
    label: 'Las Vegas',
    primaryColor: '#7C3AED',
    secondaryColor: '#FFD600',
    accentColor: '#EC4899',
    backgroundColor: '#FAF5FF',
    cardColor: '#FFFFFF',
    textColor: '#2E1065',
    mutedColor: '#7C6B8F',
    primaryRgb: '124, 58, 237',
    emoji: '🎰',
    tagline: 'SEO so good, it feels like hitting the jackpot.',
  },
  'honolulu': {
    key: 'honolulu',
    label: 'Honolulu',
    primaryColor: '#0891B2',
    secondaryColor: '#EC4899',
    accentColor: '#22D3EE',
    backgroundColor: '#ECFEFF',
    cardColor: '#FFFFFF',
    textColor: '#164E63',
    mutedColor: '#6B7280',
    primaryRgb: '8, 145, 178',
    emoji: '🌺',
    tagline: 'Aloha to your new competitors — they are behind you.',
  },

  // ────────────── New cities — batch 1 ──────────────

  'dallas': {
    key: 'dallas',
    label: 'Dallas',
    primaryColor: '#1D4ED8',
    secondaryColor: '#F97316',
    accentColor: '#FFD600',
    backgroundColor: '#EFF6FF',
    cardColor: '#FFFFFF',
    textColor: '#1E3A5F',
    mutedColor: '#6B7280',
    primaryRgb: '29, 78, 216',
    emoji: '🤠',
    tagline: 'Big D, big rankings.',
  },
  'houston': {
    key: 'houston',
    label: 'Houston',
    primaryColor: '#0F766E',
    secondaryColor: '#DC2626',
    accentColor: '#FFD600',
    backgroundColor: '#F0FDFA',
    cardColor: '#FFFFFF',
    textColor: '#134E4A',
    mutedColor: '#6B7280',
    primaryRgb: '15, 118, 110',
    emoji: '🚀',
    tagline: 'Houston, we have a solution.',
  },
  'san-diego': {
    key: 'san-diego',
    label: 'San Diego',
    primaryColor: '#1D4ED8',
    secondaryColor: '#FBBF24',
    accentColor: '#FF6B6B',
    backgroundColor: '#EFF6FF',
    cardColor: '#FFFFFF',
    textColor: '#1E3A5F',
    mutedColor: '#6B7280',
    primaryRgb: '29, 78, 216',
    emoji: '🏖️',
    tagline: 'Sunny beaches, sunnier search results.',
  },
  'san-jose': {
    key: 'san-jose',
    label: 'San Jose',
    primaryColor: '#047857',
    secondaryColor: '#14B8A6',
    accentColor: '#FACC15',
    backgroundColor: '#ECFDF5',
    cardColor: '#FFFFFF',
    textColor: '#064E3B',
    mutedColor: '#6B7280',
    primaryRgb: '4, 120, 87',
    emoji: '💻',
    tagline: 'Silicon Valley-grade SEO.',
  },
  'philadelphia': {
    key: 'philadelphia',
    label: 'Philadelphia',
    primaryColor: '#059669',
    secondaryColor: '#3B82F6',
    accentColor: '#FCD34D',
    backgroundColor: '#ECFDF5',
    cardColor: '#FFFFFF',
    textColor: '#064E3B',
    mutedColor: '#6B7280',
    primaryRgb: '5, 150, 105',
    emoji: '🔔',
    tagline: 'Ringing in results from the City of Brotherly Love.',
  },
  'san-antonio': {
    key: 'san-antonio',
    label: 'San Antonio',
    primaryColor: '#0F766E',
    secondaryColor: '#EC4899',
    accentColor: '#F97316',
    backgroundColor: '#F0FDFA',
    cardColor: '#FFFFFF',
    textColor: '#134E4A',
    mutedColor: '#6B7280',
    primaryRgb: '15, 118, 110',
    emoji: '🌮',
    tagline: 'Remember the rankings.',
  },
  'detroit': {
    key: 'detroit',
    label: 'Detroit',
    primaryColor: '#1E40AF',
    secondaryColor: '#DC2626',
    accentColor: '#94A3B8',
    backgroundColor: '#EFF6FF',
    cardColor: '#FFFFFF',
    textColor: '#1E3A5F',
    mutedColor: '#6B7280',
    primaryRgb: '30, 64, 175',
    emoji: '🚗',
    tagline: 'Built tough. Ranked tougher.',
  },
  'columbus': {
    key: 'columbus',
    label: 'Columbus',
    primaryColor: '#991B1B',
    secondaryColor: '#9CA3AF',
    accentColor: '#FACC15',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#7F1D1D',
    mutedColor: '#78716C',
    primaryRgb: '153, 27, 27',
    emoji: '🌰',
    tagline: 'Ohio proud. Page one loud.',
  },
  'indianapolis': {
    key: 'indianapolis',
    label: 'Indianapolis',
    primaryColor: '#1E40AF',
    secondaryColor: '#DC2626',
    accentColor: '#FACC15',
    backgroundColor: '#EFF6FF',
    cardColor: '#FFFFFF',
    textColor: '#172554',
    mutedColor: '#6B7280',
    primaryRgb: '30, 64, 175',
    emoji: '🏎️',
    tagline: 'Fast laps. Faster climbs.',
  },
  'jacksonville': {
    key: 'jacksonville',
    label: 'Jacksonville',
    primaryColor: '#0F766E',
    secondaryColor: '#FBBF24',
    accentColor: '#1F2937',
    backgroundColor: '#F0FDFA',
    cardColor: '#FFFFFF',
    textColor: '#134E4A',
    mutedColor: '#6B7280',
    primaryRgb: '15, 118, 110',
    emoji: '🐆',
    tagline: 'Pouncing on page one.',
  },
  'fort-worth': {
    key: 'fort-worth',
    label: 'Fort Worth',
    primaryColor: '#7F1D1D',
    secondaryColor: '#FEF3C7',
    accentColor: '#92400E',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#450A0A',
    mutedColor: '#78716C',
    primaryRgb: '127, 29, 29',
    emoji: '🤠',
    tagline: 'Where the West begins and rankings win.',
  },
  'charlotte': {
    key: 'charlotte',
    label: 'Charlotte',
    primaryColor: '#6D28D9',
    secondaryColor: '#14B8A6',
    accentColor: '#FBBF24',
    backgroundColor: '#F5F3FF',
    cardColor: '#FFFFFF',
    textColor: '#3B0764',
    mutedColor: '#6B7280',
    primaryRgb: '109, 40, 217',
    emoji: '👑',
    tagline: 'The Queen City of page one.',
  },
  'el-paso': {
    key: 'el-paso',
    label: 'El Paso',
    primaryColor: '#D97706',
    secondaryColor: '#16A34A',
    accentColor: '#0EA5E9',
    backgroundColor: '#FFFBEB',
    cardColor: '#FFFFFF',
    textColor: '#451A03',
    mutedColor: '#78716C',
    primaryRgb: '217, 119, 6',
    emoji: '🌵',
    tagline: 'Sun city, search city.',
  },
  'memphis': {
    key: 'memphis',
    label: 'Memphis',
    primaryColor: '#1E40AF',
    secondaryColor: '#DC2626',
    accentColor: '#FBBF24',
    backgroundColor: '#EFF6FF',
    cardColor: '#FFFFFF',
    textColor: '#172554',
    mutedColor: '#6B7280',
    primaryRgb: '30, 64, 175',
    emoji: '🎸',
    tagline: 'BlueSEO born and raised.',
  },
  'baltimore': {
    key: 'baltimore',
    label: 'Baltimore',
    primaryColor: '#6D28D9',
    secondaryColor: '#F97316',
    accentColor: '#1F2937',
    backgroundColor: '#F5F3FF',
    cardColor: '#FFFFFF',
    textColor: '#3B0764',
    mutedColor: '#6B7280',
    primaryRgb: '109, 40, 217',
    emoji: '🦀',
    tagline: 'Charm City charms the search engines too.',
  },
  'milwaukee': {
    key: 'milwaukee',
    label: 'Milwaukee',
    primaryColor: '#0EA5E9',
    secondaryColor: '#FDE68A',
    accentColor: '#16A34A',
    backgroundColor: '#F0F9FF',
    cardColor: '#FFFFFF',
    textColor: '#0C4A6E',
    mutedColor: '#6B7280',
    primaryRgb: '14, 165, 233',
    emoji: '🍺',
    tagline: 'Brewing up better rankings.',
  },
  'tucson': {
    key: 'tucson',
    label: 'Tucson',
    primaryColor: '#DC2626',
    secondaryColor: '#0EA5E9',
    accentColor: '#84CC16',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#7F1D1D',
    mutedColor: '#78716C',
    primaryRgb: '220, 38, 38',
    emoji: '🌵',
    tagline: 'Desert heat. Ice-cold rankings.',
  },
  'fresno': {
    key: 'fresno',
    label: 'Fresno',
    primaryColor: '#7C3AED',
    secondaryColor: '#FACC15',
    accentColor: '#22C55E',
    backgroundColor: '#F5F3FF',
    cardColor: '#FFFFFF',
    textColor: '#3B0764',
    mutedColor: '#78716C',
    primaryRgb: '124, 58, 237',
    emoji: '🍇',
    tagline: 'Raisin the bar on local SEO.',
  },
  'sacramento': {
    key: 'sacramento',
    label: 'Sacramento',
    primaryColor: '#5B21B6',
    secondaryColor: '#9CA3AF',
    accentColor: '#FBBF24',
    backgroundColor: '#F5F3FF',
    cardColor: '#FFFFFF',
    textColor: '#3B0764',
    mutedColor: '#6B7280',
    primaryRgb: '91, 33, 182',
    emoji: '🐻',
    tagline: 'Capital ideas for capital rankings.',
  },
  'mesa': {
    key: 'mesa',
    label: 'Mesa',
    primaryColor: '#C2410C',
    secondaryColor: '#A3E635',
    accentColor: '#7DD3FC',
    backgroundColor: '#FFF7ED',
    cardColor: '#FFFFFF',
    textColor: '#431407',
    mutedColor: '#78716C',
    primaryRgb: '194, 65, 12',
    emoji: '🏜️',
    tagline: 'Desert views. Page one hues.',
  },
  'kansas-city': {
    key: 'kansas-city',
    label: 'Kansas City',
    primaryColor: '#DC2626',
    secondaryColor: '#FBBF24',
    accentColor: '#2563EB',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#7F1D1D',
    mutedColor: '#78716C',
    primaryRgb: '220, 38, 38',
    emoji: '🎷',
    tagline: 'Jazzed up about your SEO.',
  },
  'washington-dc': {
    key: 'washington-dc',
    label: 'Washington D.C.',
    primaryColor: '#7F1D1D',
    secondaryColor: '#FDE68A',
    accentColor: '#1D4ED8',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#450A0A',
    mutedColor: '#78716C',
    primaryRgb: '127, 29, 29',
    emoji: '🏛️',
    tagline: 'By the people, for the rankings.',
  },
  'tampa': {
    key: 'tampa',
    label: 'Tampa',
    primaryColor: '#DC2626',
    secondaryColor: '#2563EB',
    accentColor: '#F8FAFC',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#7F1D1D',
    mutedColor: '#6B7280',
    primaryRgb: '220, 38, 38',
    emoji: '⚡',
    tagline: 'Bolting past the competition.',
  },
  'riverside': {
    key: 'riverside',
    label: 'Riverside',
    primaryColor: '#EA580C',
    secondaryColor: '#14B8A6',
    accentColor: '#FEF3C7',
    backgroundColor: '#FFF7ED',
    cardColor: '#FFFFFF',
    textColor: '#431407',
    mutedColor: '#78716C',
    primaryRgb: '234, 88, 12',
    emoji: '🍊',
    tagline: 'Growing visibility by the grove.',
  },
  'raleigh': {
    key: 'raleigh',
    label: 'Raleigh',
    primaryColor: '#DC2626',
    secondaryColor: '#F8FAFC',
    accentColor: '#1D4ED8',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#7F1D1D',
    mutedColor: '#78716C',
    primaryRgb: '220, 38, 38',
    emoji: '🌳',
    tagline: 'City of Oaks, city of clicks.',
  },
  'long-beach': {
    key: 'long-beach',
    label: 'Long Beach',
    primaryColor: '#0EA5E9',
    secondaryColor: '#FDE68A',
    accentColor: '#FF6B6B',
    backgroundColor: '#F0F9FF',
    cardColor: '#FFFFFF',
    textColor: '#0C4A6E',
    mutedColor: '#6B7280',
    primaryRgb: '14, 165, 233',
    emoji: '🏄',
    tagline: 'Catching waves and grabbing rankings.',
  },
  'virginia-beach': {
    key: 'virginia-beach',
    label: 'Virginia Beach',
    primaryColor: '#1E3A5F',
    secondaryColor: '#FDE68A',
    accentColor: '#F97316',
    backgroundColor: '#F0F5FF',
    cardColor: '#FFFFFF',
    textColor: '#0F172A',
    mutedColor: '#6B7280',
    primaryRgb: '30, 58, 95',
    emoji: '🏖️',
    tagline: 'Shore thing: your SEO is covered.',
  },
  'oakland': {
    key: 'oakland',
    label: 'Oakland',
    primaryColor: '#16A34A',
    secondaryColor: '#FACC15',
    accentColor: '#1F2937',
    backgroundColor: '#F0FDF4',
    cardColor: '#FFFFFF',
    textColor: '#14532D',
    mutedColor: '#6B7280',
    primaryRgb: '22, 163, 74',
    emoji: '🌳',
    tagline: 'Rooted in the Town. Rising in search.',
  },
  'minneapolis': {
    key: 'minneapolis',
    label: 'Minneapolis',
    primaryColor: '#6D28D9',
    secondaryColor: '#FBBF24',
    accentColor: '#93C5FD',
    backgroundColor: '#F5F3FF',
    cardColor: '#FFFFFF',
    textColor: '#3B0764',
    mutedColor: '#6B7280',
    primaryRgb: '109, 40, 217',
    emoji: '❄️',
    tagline: 'Cool under pressure. Hot on results.',
  },
  'tulsa': {
    key: 'tulsa',
    label: 'Tulsa',
    primaryColor: '#16A34A',
    secondaryColor: '#FBBF24',
    accentColor: '#1F2937',
    backgroundColor: '#F0FDF4',
    cardColor: '#FFFFFF',
    textColor: '#14532D',
    mutedColor: '#6B7280',
    primaryRgb: '22, 163, 74',
    emoji: '🎨',
    tagline: 'Art deco dreams. Top-tier rankings.',
  },
  'st-louis': {
    key: 'st-louis',
    label: 'St. Louis',
    primaryColor: '#DC2626',
    secondaryColor: '#2563EB',
    accentColor: '#FACC15',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#7F1D1D',
    mutedColor: '#78716C',
    primaryRgb: '220, 38, 38',
    emoji: '🏙️',
    tagline: 'Gateway to page one.',
  },
  'pittsburgh': {
    key: 'pittsburgh',
    label: 'Pittsburgh',
    primaryColor: '#1F2937',
    secondaryColor: '#FBBF24',
    accentColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    cardColor: '#FFFFFF',
    textColor: '#0F172A',
    mutedColor: '#6B7280',
    primaryRgb: '31, 41, 55',
    emoji: '⚙️',
    tagline: 'Steel-strong SEO foundations.',
  },
  'cleveland': {
    key: 'cleveland',
    label: 'Cleveland',
    primaryColor: '#3E2723',
    secondaryColor: '#EA580C',
    accentColor: '#F8FAFC',
    backgroundColor: '#FAFAF9',
    cardColor: '#FFFFFF',
    textColor: '#271C19',
    mutedColor: '#78716C',
    primaryRgb: '62, 39, 35',
    emoji: '🏀',
    tagline: 'Believeland believes in your rankings.',
  },
  'anaheim': {
    key: 'anaheim',
    label: 'Anaheim',
    primaryColor: '#DC2626',
    secondaryColor: '#2563EB',
    accentColor: '#F8FAFC',
    backgroundColor: '#FEF2F2',
    cardColor: '#FFFFFF',
    textColor: '#7F1D1D',
    mutedColor: '#6B7280',
    primaryRgb: '220, 38, 38',
    emoji: '🎡',
    tagline: 'The happiest place on page one.',
  },

  default: {
    key: 'default',
    label: 'Your City',
    primaryColor: '#2563EB',
    secondaryColor: '#FFD600',
    accentColor: '#FF6B6B',
    backgroundColor: '#F0F4FF',
    cardColor: '#FFFFFF',
    textColor: '#1A1A2E',
    mutedColor: '#6B7280',
    primaryRgb: '37, 99, 235',
    emoji: '📍',
    tagline: 'Local SEO, done right.',
  },
}

// Maps normalized city name input → theme key
const CITY_MAP: Record<string, ThemeKey> = {
  'los angeles': 'los-angeles',
  'la': 'los-angeles',
  'l.a.': 'los-angeles',
  'new york': 'new-york',
  'new york city': 'new-york',
  'nyc': 'new-york',
  'n.y.c.': 'new-york',
  'miami': 'miami',
  'seattle': 'seattle',
  'chicago': 'chicago',
  'austin': 'austin',
  'denver': 'denver',
  'portland': 'portland',
  'nashville': 'nashville',
  'new orleans': 'new-orleans',
  'nola': 'new-orleans',
  'san francisco': 'san-francisco',
  'sf': 'san-francisco',
  'frisco': 'san-francisco',
  'boston': 'boston',
  'atlanta': 'atlanta',
  'phoenix': 'phoenix',
  'las vegas': 'las-vegas',
  'vegas': 'las-vegas',
  'honolulu': 'honolulu',
  'dallas': 'dallas',
  'fort worth': 'fort-worth',
  'ft worth': 'fort-worth',
  'ft. worth': 'fort-worth',
  'houston': 'houston',
  'san diego': 'san-diego',
  'san jose': 'san-jose',
  'philadelphia': 'philadelphia',
  'philly': 'philadelphia',
  'san antonio': 'san-antonio',
  'detroit': 'detroit',
  'columbus': 'columbus',
  'indianapolis': 'indianapolis',
  'indy': 'indianapolis',
  'jacksonville': 'jacksonville',
  'jax': 'jacksonville',
  'charlotte': 'charlotte',
  'el paso': 'el-paso',
  'memphis': 'memphis',
  'baltimore': 'baltimore',
  'milwaukee': 'milwaukee',
  'mke': 'milwaukee',
  'tucson': 'tucson',
  'fresno': 'fresno',
  'sacramento': 'sacramento',
  'sac': 'sacramento',
  'mesa': 'mesa',
  'kansas city': 'kansas-city',
  'kc': 'kansas-city',
  'kcmo': 'kansas-city',
  'washington dc': 'washington-dc',
  'washington d.c.': 'washington-dc',
  'dc': 'washington-dc',
  'tampa': 'tampa',
  'tampa bay': 'tampa',
  'riverside': 'riverside',
  'raleigh': 'raleigh',
  'long beach': 'long-beach',
  'virginia beach': 'virginia-beach',
  'oakland': 'oakland',
  'minneapolis': 'minneapolis',
  'mpls': 'minneapolis',
  'tulsa': 'tulsa',
  'st louis': 'st-louis',
  'st. louis': 'st-louis',
  'stl': 'st-louis',
  'pittsburgh': 'pittsburgh',
  'pgh': 'pittsburgh',
  'cleveland': 'cleveland',
  'cle': 'cleveland',
  'the land': 'cleveland',
  'anaheim': 'anaheim',
}

/* Normalize a raw city string for matching:
 * - Trim whitespace
 * - Strip US state abbreviations and country suffixes (e.g. "Austin TX" → "austin")
 * - Lowercase for dictionary lookup
 */
function normalizeCity(raw: string): string {
  let s = raw.trim().toLowerCase()
  // Strip trailing state / country like "Austin TX", "Los Angeles, CA", "New York, USA"
  s = s.replace(/[,\s]+(?:al|ak|az|ar|ca|co|ct|de|fl|ga|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|oh|ok|or|pa|ri|sc|sd|tn|tx|ut|vt|va|wa|wv|wi|wy|usa|us)(?:\.)?$/i, '')
  s = s.trim()
  // Also strip just a trailing comma if it remains
  s = s.replace(/,$/, '')
  return s.trim()
}

export function getThemeForCity(city: string): CityTheme {
  const normalized = normalizeCity(city)
  const key = CITY_MAP[normalized]
  return themes[key ?? 'default']
}
